# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  timeout: 2m
  deadline: 10s
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - tools
  modules-download-mode: vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true


linters:
  disable-all: true
  enable:
    # deadcode disabled during active development
    #    - deadcode            # unused identifiers  https://github.com/remyoudompheng/go-misc/tree/master/deadcode
    - asciicheck         # non-ascii identifiers https://github.com/tdakkota/asciicheck
    - dupl               # duplicates https://github.com/mibk/dupl
    - errcheck           # unchecked err https://github.com/kisielk/errcheck
    - exportloopref      # pointers to loop vars https://github.com/kyoh86/exportloopref
    - funlen             # function length https://github.com/ultraware/funlen
    - gochecknoinits     # no init functions https://github.com/leighmcculloch/gochecknoinits
    - gocognit           # code complexity https://github.com/uudashr/gocognit
    - goconst            # find duplicated expressions https://github.com/jgautheron/goconst
    - gocritic           # various stuff https://github.com/go-critic/go-critic
    - gocyclo            # code complexity https://github.com/alecthomas/gocyclo
#    - godot              # dot in comments https://github.com/tetafro/godot
    - gofumpt            # stricter than go fmt https://github.com/mvdan/gofumpt
    - goimports          # imports https://godoc.org/golang.org/x/tools/cmd/goimports
    - gosec              # security issues  https://github.com/securego/gosec
    - gosimple           # simplify expressions https://github.com/dominikh/go-tools/tree/master/simple
    - govet              # vet https://golang.org/cmd/vet/
    - ineffassign        # ineffectual assignment https://github.com/gordonklaus/ineffassign
    - maligned           # struct alignment optimization https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment
    - misspell           # typos https://github.com/client9/misspell
    - nakedret           # naked returns https://github.com/alexkohler/nakedret
    - nestif             # nested ifs https://github.com/nakabonne/nestif # probably gocognit+gocyclo is enough
    - paralleltest       # t.Parallel() https://github.com/kunwardeep/paralleltest
    - prealloc           # slice preallocations https://github.com/alexkohler/prealloc
    - revive             # golint on steroids https://github.com/mgechev/revive
    - staticcheck        # various stuff https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck
    - stylecheck         # based on go code review comments https://github.com/dominikh/go-tools/tree/master/stylecheck
    - typecheck          # -
    - unconvert          # unnecessary conversions https://github.com/mdempsky/unconvert
    - unparam            # unused params in funcs https://github.com/mvdan/unparam
    - wsl                # whitespace https://github.com/bombsimon/wsl

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    ## - G104
    # for "public interface + private struct implementation" cases only!
    - exported func .* returns unexported type .*, which can be annoying to use
    # can be removed in the development phase
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    ##- should have a package comment, unless it's in another file for this package
    ##- don't use an underscore in package name
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    ##- should check returned error before deferring
    ##- "not declared by package utf8"
    ##- "unicode/utf8/utf8.go"

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 100
    statements: 40
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/maxkuzn/grocery-list-bot 
